import { defineClient } from "@/lib/capabilities/types";
import { barbershop } from "@/modules/barbershop";

/**
 * PER-CLIENT ASSEMBLY — generated by `npm run create-client`.
 * Capability deviations from the module go in `overrides`.
 */
export const clientConfig = defineClient({
  module: barbershop,
  overrides: {
    team: { enabled: false },
    promotions: { enabled: false },
    locations: { enabled: false },
  },
});
