import { themes, type HeaderStyle, type ThemeMeta, type ThemeName } from "@/themes";

/**
 * PER-CLIENT THEME SELECTION — generated by `npm run create-client`.
 * Color tweaks live in the palette block at the end of app/globals.css.
 */

export const activeThemeName: ThemeName = "minimal";

/** Per-client deviations from the theme's header defaults. */
const headerOverrides: Partial<HeaderStyle> = { layout: "split", sticky: true, transparent: true };

// Widened to ThemeMeta: consumers branch on motion/header for ANY theme,
// so the literal types of the selected theme must not narrow comparisons.
export const activeTheme: ThemeMeta = themes[activeThemeName];

export const headerStyle: HeaderStyle = { ...activeTheme.header, ...headerOverrides };
